name: Automated Release

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Version
        id: generate
        run: |
          $date = Get-Date -Format 'yyyy.MM.dd'
          $build_num = $env:GITHUB_RUN_NUMBER -as [int]
          $build_num = $build_num % 100
          $build_num = '{0:D2}' -f $build_num
          $build_ver = "$date.$build_num"
          echo "release_ver=$build_ver" >> $env:GITHUB_OUTPUT

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2

      - name: Zig Build
        run: zig build

      - name: Zip Bin
        run: 7z a bin.zip -r ./bin/

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          name: "${{ steps.generate.outputs.release_ver }}"
          tag: "${{ steps.generate.outputs.release_ver }}"
          artifacts: "./bin.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          